name: release-github

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  release:
    runs-on: 'ubuntu-22.04'
    defaults:
      run:
        shell: bash
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create release
        uses: ncipollo/release-action@v1.13.0
        with:
          generateReleaseNotes: true