name: release

on:
  push:
    branches:
      - 'main'
      - 'release*'

env:
  VERSION: 0.1.0

jobs:
  tag-release:
    runs-on: 'ubuntu-22.04'
    steps:
      - name: Create tag
        if: github.ref_name == 'main'
        uses: mathieudutour/github-tag-action@v6.1
        id: tag_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ env.VERSION }}
          release_branches: "main"
          pre_release_branches: "prerelease"
      - name: Create Github Release
        if: github.ref_name == 'main'
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: release-github.yml
          ref: ${{ steps.tag_version.outputs.new_tag }}
